printWidth: 120
tabWidth: 3
useTabs: false
semi: true
singleQuote: true
quoteProps: preserve
jsxSingleQuote: true
trailingComma: all
bracketSpacing: true
arrowParens: avoid
htmlWhitespaceSensitivity: strict
endOfLine: lf
